EnvironmentConfigurationMetadata:
  Description: Production configuration for Urban Palm Landscaping
  DateModified: '2026-03-10T00:00:00Z'
OptionSettings:
  aws:elasticbeanstalk:application:environment:
    NODE_ENV: production
    PORT: '8080'
  aws:elasticbeanstalk:environment:proxy:
    ProxyServer: nginx
